//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace sdkSilverlightXNACS.MiniGameService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroDataContact", Namespace="http://schemas.datacontract.org/2004/07/MiniGame.DataContractsShared")]
    public partial class HeroDataContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsInYourTeamField;
        
        private byte[] MemberPhotoField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInYourTeam {
            get {
                return this.IsInYourTeamField;
            }
            set {
                if ((this.IsInYourTeamField.Equals(value) != true)) {
                    this.IsInYourTeamField = value;
                    this.RaisePropertyChanged("IsInYourTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MemberPhoto {
            get {
                return this.MemberPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberPhotoField, value) != true)) {
                    this.MemberPhotoField = value;
                    this.RaisePropertyChanged("MemberPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Team", Namespace="http://schemas.datacontract.org/2004/07/MiniGame.DataContractsShared")]
    public partial class Team : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int BombsAddedField;
        
        private System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> HerosField;
        
        private bool IsConfirmedStartField;
        
        private bool IsLoserField;
        
        private bool IsWinnerField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BombsAdded {
            get {
                return this.BombsAddedField;
            }
            set {
                if ((this.BombsAddedField.Equals(value) != true)) {
                    this.BombsAddedField = value;
                    this.RaisePropertyChanged("BombsAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> Heros {
            get {
                return this.HerosField;
            }
            set {
                if ((object.ReferenceEquals(this.HerosField, value) != true)) {
                    this.HerosField = value;
                    this.RaisePropertyChanged("Heros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmedStart {
            get {
                return this.IsConfirmedStartField;
            }
            set {
                if ((this.IsConfirmedStartField.Equals(value) != true)) {
                    this.IsConfirmedStartField = value;
                    this.RaisePropertyChanged("IsConfirmedStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLoser {
            get {
                return this.IsLoserField;
            }
            set {
                if ((this.IsLoserField.Equals(value) != true)) {
                    this.IsLoserField = value;
                    this.RaisePropertyChanged("IsLoser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStateChanges", Namespace="http://schemas.datacontract.org/2004/07/MiniGame.DataContractsShared")]
    public partial class GameStateChanges : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int BombsAddedField;
        
        private bool IsLoserField;
        
        private bool IsWinnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BombsAdded {
            get {
                return this.BombsAddedField;
            }
            set {
                if ((this.BombsAddedField.Equals(value) != true)) {
                    this.BombsAddedField = value;
                    this.RaisePropertyChanged("BombsAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLoser {
            get {
                return this.IsLoserField;
            }
            set {
                if ((this.IsLoserField.Equals(value) != true)) {
                    this.IsLoserField = value;
                    this.RaisePropertyChanged("IsLoser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiniGameService.IMiniGameService")]
    public interface IMiniGameService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/RegisterMe", ReplyAction="http://tempuri.org/IMiniGameService/RegisterMeResponse")]
        System.IAsyncResult BeginRegisterMe(System.AsyncCallback callback, object asyncState);
        
        string EndRegisterMe(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/SetTeam", ReplyAction="http://tempuri.org/IMiniGameService/SetTeamResponse")]
        System.IAsyncResult BeginSetTeam(string myName, System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros, System.AsyncCallback callback, object asyncState);
        
        bool EndSetTeam(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/GetEnemyTeam", ReplyAction="http://tempuri.org/IMiniGameService/GetEnemyTeamResponse")]
        System.IAsyncResult BeginGetEnemyTeam(string myTeamName, System.AsyncCallback callback, object asyncState);
        
        sdkSilverlightXNACS.MiniGameService.Team EndGetEnemyTeam(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/AddBombToEnemy", ReplyAction="http://tempuri.org/IMiniGameService/AddBombToEnemyResponse")]
        System.IAsyncResult BeginAddBombToEnemy(int count, string myTeamName, System.AsyncCallback callback, object asyncState);
        
        sdkSilverlightXNACS.MiniGameService.GameStateChanges EndAddBombToEnemy(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/InformAboutWin", ReplyAction="http://tempuri.org/IMiniGameService/InformAboutWinResponse")]
        System.IAsyncResult BeginInformAboutWin(string myTeamName, System.AsyncCallback callback, object asyncState);
        
        sdkSilverlightXNACS.MiniGameService.GameStateChanges EndInformAboutWin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/InformAboutLose", ReplyAction="http://tempuri.org/IMiniGameService/InformAboutLoseResponse")]
        System.IAsyncResult BeginInformAboutLose(string myTeamName, System.AsyncCallback callback, object asyncState);
        
        sdkSilverlightXNACS.MiniGameService.GameStateChanges EndInformAboutLose(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMiniGameService/RetrieveChanges", ReplyAction="http://tempuri.org/IMiniGameService/RetrieveChangesResponse")]
        System.IAsyncResult BeginRetrieveChanges(string myTeamName, System.AsyncCallback callback, object asyncState);
        
        sdkSilverlightXNACS.MiniGameService.GameStateChanges EndRetrieveChanges(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiniGameServiceChannel : sdkSilverlightXNACS.MiniGameService.IMiniGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterMeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterMeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetTeamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetTeamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEnemyTeamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEnemyTeamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public sdkSilverlightXNACS.MiniGameService.Team Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((sdkSilverlightXNACS.MiniGameService.Team)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddBombToEnemyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddBombToEnemyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public sdkSilverlightXNACS.MiniGameService.GameStateChanges Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformAboutWinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InformAboutWinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public sdkSilverlightXNACS.MiniGameService.GameStateChanges Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformAboutLoseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InformAboutLoseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public sdkSilverlightXNACS.MiniGameService.GameStateChanges Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public sdkSilverlightXNACS.MiniGameService.GameStateChanges Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiniGameServiceClient : System.ServiceModel.ClientBase<sdkSilverlightXNACS.MiniGameService.IMiniGameService>, sdkSilverlightXNACS.MiniGameService.IMiniGameService {
        
        private BeginOperationDelegate onBeginRegisterMeDelegate;
        
        private EndOperationDelegate onEndRegisterMeDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterMeCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetTeamDelegate;
        
        private EndOperationDelegate onEndSetTeamDelegate;
        
        private System.Threading.SendOrPostCallback onSetTeamCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEnemyTeamDelegate;
        
        private EndOperationDelegate onEndGetEnemyTeamDelegate;
        
        private System.Threading.SendOrPostCallback onGetEnemyTeamCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddBombToEnemyDelegate;
        
        private EndOperationDelegate onEndAddBombToEnemyDelegate;
        
        private System.Threading.SendOrPostCallback onAddBombToEnemyCompletedDelegate;
        
        private BeginOperationDelegate onBeginInformAboutWinDelegate;
        
        private EndOperationDelegate onEndInformAboutWinDelegate;
        
        private System.Threading.SendOrPostCallback onInformAboutWinCompletedDelegate;
        
        private BeginOperationDelegate onBeginInformAboutLoseDelegate;
        
        private EndOperationDelegate onEndInformAboutLoseDelegate;
        
        private System.Threading.SendOrPostCallback onInformAboutLoseCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveChangesDelegate;
        
        private EndOperationDelegate onEndRetrieveChangesDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveChangesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MiniGameServiceClient() {
        }
        
        public MiniGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiniGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiniGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiniGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegisterMeCompletedEventArgs> RegisterMeCompleted;
        
        public event System.EventHandler<SetTeamCompletedEventArgs> SetTeamCompleted;
        
        public event System.EventHandler<GetEnemyTeamCompletedEventArgs> GetEnemyTeamCompleted;
        
        public event System.EventHandler<AddBombToEnemyCompletedEventArgs> AddBombToEnemyCompleted;
        
        public event System.EventHandler<InformAboutWinCompletedEventArgs> InformAboutWinCompleted;
        
        public event System.EventHandler<InformAboutLoseCompletedEventArgs> InformAboutLoseCompleted;
        
        public event System.EventHandler<RetrieveChangesCompletedEventArgs> RetrieveChangesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginRegisterMe(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterMe(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndRegisterMe(System.IAsyncResult result) {
            return base.Channel.EndRegisterMe(result);
        }
        
        private System.IAsyncResult OnBeginRegisterMe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginRegisterMe(callback, asyncState);
        }
        
        private object[] OnEndRegisterMe(System.IAsyncResult result) {
            string retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndRegisterMe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterMeCompleted(object state) {
            if ((this.RegisterMeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterMeCompleted(this, new RegisterMeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterMeAsync() {
            this.RegisterMeAsync(null);
        }
        
        public void RegisterMeAsync(object userState) {
            if ((this.onBeginRegisterMeDelegate == null)) {
                this.onBeginRegisterMeDelegate = new BeginOperationDelegate(this.OnBeginRegisterMe);
            }
            if ((this.onEndRegisterMeDelegate == null)) {
                this.onEndRegisterMeDelegate = new EndOperationDelegate(this.OnEndRegisterMe);
            }
            if ((this.onRegisterMeCompletedDelegate == null)) {
                this.onRegisterMeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterMeCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterMeDelegate, null, this.onEndRegisterMeDelegate, this.onRegisterMeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginSetTeam(string myName, System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetTeam(myName, myHeros, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndSetTeam(System.IAsyncResult result) {
            return base.Channel.EndSetTeam(result);
        }
        
        private System.IAsyncResult OnBeginSetTeam(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string myName = ((string)(inValues[0]));
            System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros = ((System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact>)(inValues[1]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginSetTeam(myName, myHeros, callback, asyncState);
        }
        
        private object[] OnEndSetTeam(System.IAsyncResult result) {
            bool retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndSetTeam(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetTeamCompleted(object state) {
            if ((this.SetTeamCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetTeamCompleted(this, new SetTeamCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetTeamAsync(string myName, System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros) {
            this.SetTeamAsync(myName, myHeros, null);
        }
        
        public void SetTeamAsync(string myName, System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros, object userState) {
            if ((this.onBeginSetTeamDelegate == null)) {
                this.onBeginSetTeamDelegate = new BeginOperationDelegate(this.OnBeginSetTeam);
            }
            if ((this.onEndSetTeamDelegate == null)) {
                this.onEndSetTeamDelegate = new EndOperationDelegate(this.OnEndSetTeam);
            }
            if ((this.onSetTeamCompletedDelegate == null)) {
                this.onSetTeamCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetTeamCompleted);
            }
            base.InvokeAsync(this.onBeginSetTeamDelegate, new object[] {
                        myName,
                        myHeros}, this.onEndSetTeamDelegate, this.onSetTeamCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginGetEnemyTeam(string myTeamName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEnemyTeam(myTeamName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdkSilverlightXNACS.MiniGameService.Team sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndGetEnemyTeam(System.IAsyncResult result) {
            return base.Channel.EndGetEnemyTeam(result);
        }
        
        private System.IAsyncResult OnBeginGetEnemyTeam(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string myTeamName = ((string)(inValues[0]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginGetEnemyTeam(myTeamName, callback, asyncState);
        }
        
        private object[] OnEndGetEnemyTeam(System.IAsyncResult result) {
            sdkSilverlightXNACS.MiniGameService.Team retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndGetEnemyTeam(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEnemyTeamCompleted(object state) {
            if ((this.GetEnemyTeamCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEnemyTeamCompleted(this, new GetEnemyTeamCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEnemyTeamAsync(string myTeamName) {
            this.GetEnemyTeamAsync(myTeamName, null);
        }
        
        public void GetEnemyTeamAsync(string myTeamName, object userState) {
            if ((this.onBeginGetEnemyTeamDelegate == null)) {
                this.onBeginGetEnemyTeamDelegate = new BeginOperationDelegate(this.OnBeginGetEnemyTeam);
            }
            if ((this.onEndGetEnemyTeamDelegate == null)) {
                this.onEndGetEnemyTeamDelegate = new EndOperationDelegate(this.OnEndGetEnemyTeam);
            }
            if ((this.onGetEnemyTeamCompletedDelegate == null)) {
                this.onGetEnemyTeamCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEnemyTeamCompleted);
            }
            base.InvokeAsync(this.onBeginGetEnemyTeamDelegate, new object[] {
                        myTeamName}, this.onEndGetEnemyTeamDelegate, this.onGetEnemyTeamCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginAddBombToEnemy(int count, string myTeamName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddBombToEnemy(count, myTeamName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdkSilverlightXNACS.MiniGameService.GameStateChanges sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndAddBombToEnemy(System.IAsyncResult result) {
            return base.Channel.EndAddBombToEnemy(result);
        }
        
        private System.IAsyncResult OnBeginAddBombToEnemy(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int count = ((int)(inValues[0]));
            string myTeamName = ((string)(inValues[1]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginAddBombToEnemy(count, myTeamName, callback, asyncState);
        }
        
        private object[] OnEndAddBombToEnemy(System.IAsyncResult result) {
            sdkSilverlightXNACS.MiniGameService.GameStateChanges retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndAddBombToEnemy(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddBombToEnemyCompleted(object state) {
            if ((this.AddBombToEnemyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddBombToEnemyCompleted(this, new AddBombToEnemyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddBombToEnemyAsync(int count, string myTeamName) {
            this.AddBombToEnemyAsync(count, myTeamName, null);
        }
        
        public void AddBombToEnemyAsync(int count, string myTeamName, object userState) {
            if ((this.onBeginAddBombToEnemyDelegate == null)) {
                this.onBeginAddBombToEnemyDelegate = new BeginOperationDelegate(this.OnBeginAddBombToEnemy);
            }
            if ((this.onEndAddBombToEnemyDelegate == null)) {
                this.onEndAddBombToEnemyDelegate = new EndOperationDelegate(this.OnEndAddBombToEnemy);
            }
            if ((this.onAddBombToEnemyCompletedDelegate == null)) {
                this.onAddBombToEnemyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddBombToEnemyCompleted);
            }
            base.InvokeAsync(this.onBeginAddBombToEnemyDelegate, new object[] {
                        count,
                        myTeamName}, this.onEndAddBombToEnemyDelegate, this.onAddBombToEnemyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginInformAboutWin(string myTeamName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInformAboutWin(myTeamName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdkSilverlightXNACS.MiniGameService.GameStateChanges sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndInformAboutWin(System.IAsyncResult result) {
            return base.Channel.EndInformAboutWin(result);
        }
        
        private System.IAsyncResult OnBeginInformAboutWin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string myTeamName = ((string)(inValues[0]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginInformAboutWin(myTeamName, callback, asyncState);
        }
        
        private object[] OnEndInformAboutWin(System.IAsyncResult result) {
            sdkSilverlightXNACS.MiniGameService.GameStateChanges retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndInformAboutWin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInformAboutWinCompleted(object state) {
            if ((this.InformAboutWinCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InformAboutWinCompleted(this, new InformAboutWinCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InformAboutWinAsync(string myTeamName) {
            this.InformAboutWinAsync(myTeamName, null);
        }
        
        public void InformAboutWinAsync(string myTeamName, object userState) {
            if ((this.onBeginInformAboutWinDelegate == null)) {
                this.onBeginInformAboutWinDelegate = new BeginOperationDelegate(this.OnBeginInformAboutWin);
            }
            if ((this.onEndInformAboutWinDelegate == null)) {
                this.onEndInformAboutWinDelegate = new EndOperationDelegate(this.OnEndInformAboutWin);
            }
            if ((this.onInformAboutWinCompletedDelegate == null)) {
                this.onInformAboutWinCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInformAboutWinCompleted);
            }
            base.InvokeAsync(this.onBeginInformAboutWinDelegate, new object[] {
                        myTeamName}, this.onEndInformAboutWinDelegate, this.onInformAboutWinCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginInformAboutLose(string myTeamName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInformAboutLose(myTeamName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdkSilverlightXNACS.MiniGameService.GameStateChanges sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndInformAboutLose(System.IAsyncResult result) {
            return base.Channel.EndInformAboutLose(result);
        }
        
        private System.IAsyncResult OnBeginInformAboutLose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string myTeamName = ((string)(inValues[0]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginInformAboutLose(myTeamName, callback, asyncState);
        }
        
        private object[] OnEndInformAboutLose(System.IAsyncResult result) {
            sdkSilverlightXNACS.MiniGameService.GameStateChanges retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndInformAboutLose(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInformAboutLoseCompleted(object state) {
            if ((this.InformAboutLoseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InformAboutLoseCompleted(this, new InformAboutLoseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InformAboutLoseAsync(string myTeamName) {
            this.InformAboutLoseAsync(myTeamName, null);
        }
        
        public void InformAboutLoseAsync(string myTeamName, object userState) {
            if ((this.onBeginInformAboutLoseDelegate == null)) {
                this.onBeginInformAboutLoseDelegate = new BeginOperationDelegate(this.OnBeginInformAboutLose);
            }
            if ((this.onEndInformAboutLoseDelegate == null)) {
                this.onEndInformAboutLoseDelegate = new EndOperationDelegate(this.OnEndInformAboutLose);
            }
            if ((this.onInformAboutLoseCompletedDelegate == null)) {
                this.onInformAboutLoseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInformAboutLoseCompleted);
            }
            base.InvokeAsync(this.onBeginInformAboutLoseDelegate, new object[] {
                        myTeamName}, this.onEndInformAboutLoseDelegate, this.onInformAboutLoseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult sdkSilverlightXNACS.MiniGameService.IMiniGameService.BeginRetrieveChanges(string myTeamName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveChanges(myTeamName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdkSilverlightXNACS.MiniGameService.GameStateChanges sdkSilverlightXNACS.MiniGameService.IMiniGameService.EndRetrieveChanges(System.IAsyncResult result) {
            return base.Channel.EndRetrieveChanges(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveChanges(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string myTeamName = ((string)(inValues[0]));
            return ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).BeginRetrieveChanges(myTeamName, callback, asyncState);
        }
        
        private object[] OnEndRetrieveChanges(System.IAsyncResult result) {
            sdkSilverlightXNACS.MiniGameService.GameStateChanges retVal = ((sdkSilverlightXNACS.MiniGameService.IMiniGameService)(this)).EndRetrieveChanges(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveChangesCompleted(object state) {
            if ((this.RetrieveChangesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveChangesCompleted(this, new RetrieveChangesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveChangesAsync(string myTeamName) {
            this.RetrieveChangesAsync(myTeamName, null);
        }
        
        public void RetrieveChangesAsync(string myTeamName, object userState) {
            if ((this.onBeginRetrieveChangesDelegate == null)) {
                this.onBeginRetrieveChangesDelegate = new BeginOperationDelegate(this.OnBeginRetrieveChanges);
            }
            if ((this.onEndRetrieveChangesDelegate == null)) {
                this.onEndRetrieveChangesDelegate = new EndOperationDelegate(this.OnEndRetrieveChanges);
            }
            if ((this.onRetrieveChangesCompletedDelegate == null)) {
                this.onRetrieveChangesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveChangesCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveChangesDelegate, new object[] {
                        myTeamName}, this.onEndRetrieveChangesDelegate, this.onRetrieveChangesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override sdkSilverlightXNACS.MiniGameService.IMiniGameService CreateChannel() {
            return new MiniGameServiceClientChannel(this);
        }
        
        private class MiniGameServiceClientChannel : ChannelBase<sdkSilverlightXNACS.MiniGameService.IMiniGameService>, sdkSilverlightXNACS.MiniGameService.IMiniGameService {
            
            public MiniGameServiceClientChannel(System.ServiceModel.ClientBase<sdkSilverlightXNACS.MiniGameService.IMiniGameService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegisterMe(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RegisterMe", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegisterMe(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RegisterMe", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetTeam(string myName, System.Collections.Generic.List<sdkSilverlightXNACS.MiniGameService.HeroDataContact> myHeros, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = myName;
                _args[1] = myHeros;
                System.IAsyncResult _result = base.BeginInvoke("SetTeam", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSetTeam(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SetTeam", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEnemyTeam(string myTeamName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = myTeamName;
                System.IAsyncResult _result = base.BeginInvoke("GetEnemyTeam", _args, callback, asyncState);
                return _result;
            }
            
            public sdkSilverlightXNACS.MiniGameService.Team EndGetEnemyTeam(System.IAsyncResult result) {
                object[] _args = new object[0];
                sdkSilverlightXNACS.MiniGameService.Team _result = ((sdkSilverlightXNACS.MiniGameService.Team)(base.EndInvoke("GetEnemyTeam", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddBombToEnemy(int count, string myTeamName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = count;
                _args[1] = myTeamName;
                System.IAsyncResult _result = base.BeginInvoke("AddBombToEnemy", _args, callback, asyncState);
                return _result;
            }
            
            public sdkSilverlightXNACS.MiniGameService.GameStateChanges EndAddBombToEnemy(System.IAsyncResult result) {
                object[] _args = new object[0];
                sdkSilverlightXNACS.MiniGameService.GameStateChanges _result = ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(base.EndInvoke("AddBombToEnemy", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInformAboutWin(string myTeamName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = myTeamName;
                System.IAsyncResult _result = base.BeginInvoke("InformAboutWin", _args, callback, asyncState);
                return _result;
            }
            
            public sdkSilverlightXNACS.MiniGameService.GameStateChanges EndInformAboutWin(System.IAsyncResult result) {
                object[] _args = new object[0];
                sdkSilverlightXNACS.MiniGameService.GameStateChanges _result = ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(base.EndInvoke("InformAboutWin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInformAboutLose(string myTeamName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = myTeamName;
                System.IAsyncResult _result = base.BeginInvoke("InformAboutLose", _args, callback, asyncState);
                return _result;
            }
            
            public sdkSilverlightXNACS.MiniGameService.GameStateChanges EndInformAboutLose(System.IAsyncResult result) {
                object[] _args = new object[0];
                sdkSilverlightXNACS.MiniGameService.GameStateChanges _result = ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(base.EndInvoke("InformAboutLose", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveChanges(string myTeamName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = myTeamName;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveChanges", _args, callback, asyncState);
                return _result;
            }
            
            public sdkSilverlightXNACS.MiniGameService.GameStateChanges EndRetrieveChanges(System.IAsyncResult result) {
                object[] _args = new object[0];
                sdkSilverlightXNACS.MiniGameService.GameStateChanges _result = ((sdkSilverlightXNACS.MiniGameService.GameStateChanges)(base.EndInvoke("RetrieveChanges", _args, result)));
                return _result;
            }
        }
    }
}
