//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WCEmergency.DataLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WCEmergencyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WCEmergencyEntities object using the connection string found in the 'WCEmergencyEntities' section of the application configuration file.
        /// </summary>
        public WCEmergencyEntities() : base("name=WCEmergencyEntities", "WCEmergencyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCEmergencyEntities object.
        /// </summary>
        public WCEmergencyEntities(string connectionString) : base(connectionString, "WCEmergencyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCEmergencyEntities object.
        /// </summary>
        public WCEmergencyEntities(EntityConnection connection) : base(connection, "WCEmergencyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Toilet> Toilets
        {
            get
            {
                if ((_Toilets == null))
                {
                    _Toilets = base.CreateObjectSet<Toilet>("Toilets");
                }
                return _Toilets;
            }
        }
        private ObjectSet<Toilet> _Toilets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Toilets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToilets(Toilet toilet)
        {
            base.AddObject("Toilets", toilet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WCEmergencyModel", Name="Toilet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Toilet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Toilet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sex">Initial value of the Sex property.</param>
        /// <param name="coordinateX">Initial value of the CoordinateX property.</param>
        /// <param name="coordinateY">Initial value of the CoordinateY property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        public static Toilet CreateToilet(global::System.Int32 id, global::System.String name, global::System.Int32 sex, global::System.Double coordinateX, global::System.Double coordinateY, global::System.DateTime dateAdded)
        {
            Toilet toilet = new Toilet();
            toilet.Id = id;
            toilet.Name = name;
            toilet.Sex = sex;
            toilet.CoordinateX = coordinateX;
            toilet.CoordinateY = coordinateY;
            toilet.DateAdded = dateAdded;
            return toilet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private Nullable<global::System.Int32> _Rate;
        partial void OnRateChanging(Nullable<global::System.Int32> value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.Int32 _Sex;
        partial void OnSexChanging(global::System.Int32 value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CoordinateX
        {
            get
            {
                return _CoordinateX;
            }
            set
            {
                OnCoordinateXChanging(value);
                ReportPropertyChanging("CoordinateX");
                _CoordinateX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoordinateX");
                OnCoordinateXChanged();
            }
        }
        private global::System.Double _CoordinateX;
        partial void OnCoordinateXChanging(global::System.Double value);
        partial void OnCoordinateXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CoordinateY
        {
            get
            {
                return _CoordinateY;
            }
            set
            {
                OnCoordinateYChanging(value);
                ReportPropertyChanging("CoordinateY");
                _CoordinateY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoordinateY");
                OnCoordinateYChanged();
            }
        }
        private global::System.Double _CoordinateY;
        partial void OnCoordinateYChanging(global::System.Double value);
        partial void OnCoordinateYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();

        #endregion
    
    }

    #endregion
    
}
