//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WP7PizzaDelivery.PizzaDelivery {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateMileageRequest", Namespace="http://schemas.datacontract.org/2004/07/PizzaDeliveryServices")]
    public partial class CalculateMileageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EndAddressField;
        
        private System.Nullable<double> EndLatitudeField;
        
        private System.Nullable<double> EndLongitudeField;
        
        private string StartAddressField;
        
        private System.Nullable<double> StartLatitudeField;
        
        private System.Nullable<double> StartLongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndAddress {
            get {
                return this.EndAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EndAddressField, value) != true)) {
                    this.EndAddressField = value;
                    this.RaisePropertyChanged("EndAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EndLatitude {
            get {
                return this.EndLatitudeField;
            }
            set {
                if ((this.EndLatitudeField.Equals(value) != true)) {
                    this.EndLatitudeField = value;
                    this.RaisePropertyChanged("EndLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EndLongitude {
            get {
                return this.EndLongitudeField;
            }
            set {
                if ((this.EndLongitudeField.Equals(value) != true)) {
                    this.EndLongitudeField = value;
                    this.RaisePropertyChanged("EndLongitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartAddress {
            get {
                return this.StartAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StartAddressField, value) != true)) {
                    this.StartAddressField = value;
                    this.RaisePropertyChanged("StartAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StartLatitude {
            get {
                return this.StartLatitudeField;
            }
            set {
                if ((this.StartLatitudeField.Equals(value) != true)) {
                    this.StartLatitudeField = value;
                    this.RaisePropertyChanged("StartLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StartLongitude {
            get {
                return this.StartLongitudeField;
            }
            set {
                if ((this.StartLongitudeField.Equals(value) != true)) {
                    this.StartLongitudeField = value;
                    this.RaisePropertyChanged("StartLongitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateMileageResult", Namespace="http://schemas.datacontract.org/2004/07/PizzaDeliveryServices")]
    public partial class CalculateMileageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        private double MileageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateRouteRequest", Namespace="http://schemas.datacontract.org/2004/07/PizzaDeliveryServices")]
    public partial class CalculateRouteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EndAddressField;
        
        private System.Nullable<double> EndLatitudeField;
        
        private System.Nullable<double> EndLongitudeField;
        
        private string StartAddressField;
        
        private System.Nullable<double> StartLatitudeField;
        
        private System.Nullable<double> StartLongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndAddress {
            get {
                return this.EndAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EndAddressField, value) != true)) {
                    this.EndAddressField = value;
                    this.RaisePropertyChanged("EndAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EndLatitude {
            get {
                return this.EndLatitudeField;
            }
            set {
                if ((this.EndLatitudeField.Equals(value) != true)) {
                    this.EndLatitudeField = value;
                    this.RaisePropertyChanged("EndLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EndLongitude {
            get {
                return this.EndLongitudeField;
            }
            set {
                if ((this.EndLongitudeField.Equals(value) != true)) {
                    this.EndLongitudeField = value;
                    this.RaisePropertyChanged("EndLongitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartAddress {
            get {
                return this.StartAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StartAddressField, value) != true)) {
                    this.StartAddressField = value;
                    this.RaisePropertyChanged("StartAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StartLatitude {
            get {
                return this.StartLatitudeField;
            }
            set {
                if ((this.StartLatitudeField.Equals(value) != true)) {
                    this.StartLatitudeField = value;
                    this.RaisePropertyChanged("StartLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StartLongitude {
            get {
                return this.StartLongitudeField;
            }
            set {
                if ((this.StartLongitudeField.Equals(value) != true)) {
                    this.StartLongitudeField = value;
                    this.RaisePropertyChanged("StartLongitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateRouteResult", Namespace="http://schemas.datacontract.org/2004/07/PizzaDeliveryServices")]
    public partial class CalculateRouteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<WP7PizzaDelivery.PizzaDelivery.RouteDirectionModel> DirectionsField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WP7PizzaDelivery.PizzaDelivery.RouteDirectionModel> Directions {
            get {
                return this.DirectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionsField, value) != true)) {
                    this.DirectionsField = value;
                    this.RaisePropertyChanged("Directions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteDirectionModel", Namespace="http://schemas.datacontract.org/2004/07/PizzaDeliveryServices")]
    public partial class RouteDirectionModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private int IndexField;
        
        private double MileageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaDelivery.IPizzaDelivery")]
    public interface IPizzaDelivery {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPizzaDelivery/Ping", ReplyAction="http://tempuri.org/IPizzaDelivery/PingResponse")]
        System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState);
        
        string EndPing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPizzaDelivery/CalculateMileage", ReplyAction="http://tempuri.org/IPizzaDelivery/CalculateMileageResponse")]
        System.IAsyncResult BeginCalculateMileage(WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request, System.AsyncCallback callback, object asyncState);
        
        WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult EndCalculateMileage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPizzaDelivery/CalculateRoute", ReplyAction="http://tempuri.org/IPizzaDelivery/CalculateRouteResponse")]
        System.IAsyncResult BeginCalculateRoute(WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request, System.AsyncCallback callback, object asyncState);
        
        WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult EndCalculateRoute(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaDeliveryChannel : WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateMileageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalculateMileageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalculateRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaDeliveryClient : System.ServiceModel.ClientBase<WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery>, WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery {
        
        private BeginOperationDelegate onBeginPingDelegate;
        
        private EndOperationDelegate onEndPingDelegate;
        
        private System.Threading.SendOrPostCallback onPingCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalculateMileageDelegate;
        
        private EndOperationDelegate onEndCalculateMileageDelegate;
        
        private System.Threading.SendOrPostCallback onCalculateMileageCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalculateRouteDelegate;
        
        private EndOperationDelegate onEndCalculateRouteDelegate;
        
        private System.Threading.SendOrPostCallback onCalculateRouteCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PizzaDeliveryClient() {
        }
        
        public PizzaDeliveryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaDeliveryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDeliveryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDeliveryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PingCompletedEventArgs> PingCompleted;
        
        public event System.EventHandler<CalculateMileageCompletedEventArgs> CalculateMileageCompleted;
        
        public event System.EventHandler<CalculateRouteCompletedEventArgs> CalculateRouteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.BeginPing(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPing(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.EndPing(System.IAsyncResult result) {
            return base.Channel.EndPing(result);
        }
        
        private System.IAsyncResult OnBeginPing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).BeginPing(callback, asyncState);
        }
        
        private object[] OnEndPing(System.IAsyncResult result) {
            string retVal = ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).EndPing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPingCompleted(object state) {
            if ((this.PingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PingCompleted(this, new PingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        public void PingAsync(object userState) {
            if ((this.onBeginPingDelegate == null)) {
                this.onBeginPingDelegate = new BeginOperationDelegate(this.OnBeginPing);
            }
            if ((this.onEndPingDelegate == null)) {
                this.onEndPingDelegate = new EndOperationDelegate(this.OnEndPing);
            }
            if ((this.onPingCompletedDelegate == null)) {
                this.onPingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPingCompleted);
            }
            base.InvokeAsync(this.onBeginPingDelegate, null, this.onEndPingDelegate, this.onPingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.BeginCalculateMileage(WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalculateMileage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.EndCalculateMileage(System.IAsyncResult result) {
            return base.Channel.EndCalculateMileage(result);
        }
        
        private System.IAsyncResult OnBeginCalculateMileage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request = ((WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest)(inValues[0]));
            return ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).BeginCalculateMileage(request, callback, asyncState);
        }
        
        private object[] OnEndCalculateMileage(System.IAsyncResult result) {
            WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult retVal = ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).EndCalculateMileage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalculateMileageCompleted(object state) {
            if ((this.CalculateMileageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalculateMileageCompleted(this, new CalculateMileageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalculateMileageAsync(WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request) {
            this.CalculateMileageAsync(request, null);
        }
        
        public void CalculateMileageAsync(WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request, object userState) {
            if ((this.onBeginCalculateMileageDelegate == null)) {
                this.onBeginCalculateMileageDelegate = new BeginOperationDelegate(this.OnBeginCalculateMileage);
            }
            if ((this.onEndCalculateMileageDelegate == null)) {
                this.onEndCalculateMileageDelegate = new EndOperationDelegate(this.OnEndCalculateMileage);
            }
            if ((this.onCalculateMileageCompletedDelegate == null)) {
                this.onCalculateMileageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalculateMileageCompleted);
            }
            base.InvokeAsync(this.onBeginCalculateMileageDelegate, new object[] {
                        request}, this.onEndCalculateMileageDelegate, this.onCalculateMileageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.BeginCalculateRoute(WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalculateRoute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery.EndCalculateRoute(System.IAsyncResult result) {
            return base.Channel.EndCalculateRoute(result);
        }
        
        private System.IAsyncResult OnBeginCalculateRoute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request = ((WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest)(inValues[0]));
            return ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).BeginCalculateRoute(request, callback, asyncState);
        }
        
        private object[] OnEndCalculateRoute(System.IAsyncResult result) {
            WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult retVal = ((WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery)(this)).EndCalculateRoute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalculateRouteCompleted(object state) {
            if ((this.CalculateRouteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalculateRouteCompleted(this, new CalculateRouteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalculateRouteAsync(WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request) {
            this.CalculateRouteAsync(request, null);
        }
        
        public void CalculateRouteAsync(WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request, object userState) {
            if ((this.onBeginCalculateRouteDelegate == null)) {
                this.onBeginCalculateRouteDelegate = new BeginOperationDelegate(this.OnBeginCalculateRoute);
            }
            if ((this.onEndCalculateRouteDelegate == null)) {
                this.onEndCalculateRouteDelegate = new EndOperationDelegate(this.OnEndCalculateRoute);
            }
            if ((this.onCalculateRouteCompletedDelegate == null)) {
                this.onCalculateRouteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalculateRouteCompleted);
            }
            base.InvokeAsync(this.onBeginCalculateRouteDelegate, new object[] {
                        request}, this.onEndCalculateRouteDelegate, this.onCalculateRouteCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery CreateChannel() {
            return new PizzaDeliveryClientChannel(this);
        }
        
        private class PizzaDeliveryClientChannel : ChannelBase<WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery>, WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery {
            
            public PizzaDeliveryClientChannel(System.ServiceModel.ClientBase<WP7PizzaDelivery.PizzaDelivery.IPizzaDelivery> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Ping", _args, callback, asyncState);
                return _result;
            }
            
            public string EndPing(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Ping", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCalculateMileage(WP7PizzaDelivery.PizzaDelivery.CalculateMileageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CalculateMileage", _args, callback, asyncState);
                return _result;
            }
            
            public WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult EndCalculateMileage(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult _result = ((WP7PizzaDelivery.PizzaDelivery.CalculateMileageResult)(base.EndInvoke("CalculateMileage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCalculateRoute(WP7PizzaDelivery.PizzaDelivery.CalculateRouteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CalculateRoute", _args, callback, asyncState);
                return _result;
            }
            
            public WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult EndCalculateRoute(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult _result = ((WP7PizzaDelivery.PizzaDelivery.CalculateRouteResult)(base.EndInvoke("CalculateRoute", _args, result)));
                return _result;
            }
        }
    }
}
